---
title: "Project 2"
author: "Collin McGuire"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Part 1 - Loading Necessary Packages}
library(tidyverse)
library(tidytuesdayR)
```

```{r Part 1A - Exponential Transformation}
## Think this works now, what a diff sleep makes
Exp <- function(x, k){
  if(k == 1) {
   result <- 1 + x
  } else if(k == 2) {
      result <- 1 + x + (x^k)/factorial(k)
  } else{
      l = (k-1)
      output3 <- vector("double", length= l)
      for(i in 2:k) {
        output3[[i]] <- (x^i)/factorial(i)
      }
      expon_tot <- sum(output3)
      result <- 1 + x + expon_tot
  }
  print(result)
}

Exp(1, 4)
```
```{r Test code}
sample_sd(testy)
sd(testy)
alpha = 1 - 0.95
dof <- 10-1
t_score = qt(p=alpha/2, df = dof, lower.tail = FALSE)
upper <- (t_score*sd(testy) + mean(testy))
lower <- (t_score*sd(testy) - mean(testy))
  answer <- c(lower, upper)
```



```{r Part 1B - Sample Mean and Std Dev}

sample_mean <- function(x) {
  arith_mean <- sum(x)/length(x)
}
testy <- rbinom(10, 5, 0.5)
sample_mean(testy)
  
sample_sd <- function(x) {
  l <- length(x)
  m <- sum(x)/l
  dif <- x-m
  sq_dif <- dif^2
  sum_dif <- sum(sq_dif)
  under_sqrt <- sum_dif/(l-1)
  sd_result <- sqrt(under_sqrt)
}
sample_sd(testy)
```


```{r Part 1C - Confidence Intervals}
calculate_CI <- function(x, conf) {
  
  if(conf >= 1) {
    stop("Confidence interval values must be <1 and >0. For a 95% CI, use 0.95")
    
  } else if(conf <= 0) {
    stop("Confidence interval values must be <1 and >0. For a 95% CI, use 0.95")
    
  }
  
  
  alpha = 1 - conf
  N <- length(x)
  dof <- length(x)-1
  t_score = qt(p=alpha/2, df = dof, lower.tail = FALSE)
  std_error <- sample_sd(x)/sqrt(N)
  
  lower <- sample_mean(x) - t_score*std_error
  upper <- sample_mean(x) + t_score*std_error
  
  answer <- c(lower, upper)
  return(answer)
}
calculate_CI(testy, conf = 0.95)

```


```{r Part 2 - Wrangling Data Part 1}
library(here)
library(lubridate)
library(stringr)
if(!file.exists(here("data","tuesdata_rainfall.RDS"))){
  tuesdata <- tidytuesdayR::tt_load('2020-01-07')
  rainfall <- tuesdata$rainfall
  temperature <- tuesdata$temperature
  
  # save the files to RDS objects
  saveRDS(tuesdata$rainfall, file= here("data","tuesdata_rainfall.RDS"))
  saveRDS(tuesdata$temperature, file= here("data","tuesdata_temperature.RDS"))
}

rainfall <- readRDS(here("data","tuesdata_rainfall.RDS"))
temperature <- readRDS(here("data","tuesdata_temperature.RDS"))

rainfall <- rainfall %>%
  drop_na() %>%
  mutate(date = make_date(year, month, day)) %>%
  mutate(city_name = toupper(city_name)) %>%
  select(-3, -4, -5)
year <- year(ymd(rainfall$date))
merged <- rainfall %>%
  mutate(year = year) %>%
  inner_join(temperature, by = c("city_name", "date"))
```

```{r Part 3: Data Visualization}
library(ggplot2)
twentyfourteen <- merged %>%
  filter(year >= 2014)

```

```{r Part 3A: Plotting temperature data over time, fig.width = 12, fig.height= 8}
base3A <- ggplot(twentyfourteen, aes(x = date, y = temperature, color = temp_type))
base3A + geom_line() +
  facet_wrap(city_name ~ ., scales = "free", ncol = 1)

```


```{r Part 3B: Plotting rainfall over time}
histogram_plot <- function(df, x, y) {
  if((! (x %in% df$city_name)) | (! (y %in% df$year))) {
    stop("This input does not exist in the dataset")
  }
  
  histogram <- df %>% 
    filter(city_name == x, year == y) %>%
    ggplot(aes(x = log(rainfall))) +
    geom_histogram() 
  
  print(histogram)
}

histogram_plot(merged, "PERTH", 2016)

```

```{r Part 4A: Tasks}
rain_df <- merged %>%
  filter(year >= 2014) %>%
  group_by(city_name, year) %>%
  summarize(average_rainfall = sample_mean(rainfall),
            Std_Dev_rainfall = sample_sd(rainfall),
            lower_bound = calculate_CI(rainfall, conf = 0.95)[1],
            upper_bound = calculate_CI(rainfall, conf = 0.95)[2], .groups = "keep")

```


```{r Part 4B: Tasks}
part4 <- rain_df %>% 
  ggplot(aes(x = year, average_rainfall))+ 
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin = rain_df$lower_bound, ymax = rain_df$upper_bound)) +
  facet_wrap(city_name ~ .)

part4

```

